=== ALJ00/lm-xml-dtds/02_ejercicios/02_agenda/agenda.dtd
<!ELEMENT agenda (contacto*)>

<!ELEMENT contacto ( nombre, direccion, ciudad, provincia, cp,
        numeros, email, web, companyia)>

<!ELEMENT nombre (#PCDATA)>
        <!ELEMENT direccion (#PCDATA)>
        <!ELEMENT ciudad (#PCDATA)>
        <!ELEMENT provincia (#PCDATA)>
        <!ELEMENT cp (#PCDATA)>
        <!ELEMENT telefono (#PCDATA)>
        <!ELEMENT fax (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT web (#PCDATA)>
        <!ELEMENT companyia (#PCDATA)>

<!ELEMENT numeros (telefono,fax)>

=== ALJ00/lm-xml-dtds/02_ejercicios/02_agenda/agenda.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">
<agenda>
    <contacto>
        <nombre>Pedro casas</nombre>
        <direccion> Calle avalladolid </direccion>
        <ciudad> Vitoria </ciudad>
        <provincia>Alava</provincia>
        <cp>01003</cp>
        <numeros>
            <telefono>896</telefono>
            <fax>3654</fax>
        </numeros>
        <email>@gmail</email>
        <web>milop.com</web>
        <companyia>mercedes</companyia>
    </contacto>
</agenda>
